permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

title : 阅读列表
author :
  name : readlist
  
production_url : http://readlist.github.com
JB :
  version : 0.2.13
  BASE_PATH : false
  ASSET_PATH : false
  
  archive_path : /archive.html
  categoriess_path : /categories.html
  tags_path : /tags.html
  
  analytics :
     provider : google 
     google : 
         tracking_id : 'UA-30079913-1'
  
  